spring:
  jpa:
    properties:
      eclipselink:
        logging:
          level:
            ROOT: INFO
            sql: INFO
  datasource:
    initialize: true
    #schema: classpath:/db/tables/hsql_database_tables.sql,classpath:/db/tables/security-schema.sql
logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO
server:
  port: 8080
  contextPath: / 
 
openid:
  connect:
    server:
      host: localhost
      issuer: http://${openid.connect.server.host}:${server.port}${server.contextPath}
      topbarTitle: OpenID Connect Server
      logoImageUrl: resources/images/openid_connect_small.png
      regTokenLifeTime: 172800
      forceHttps: false
      rqpTokenLifeTime: 
      locale: en
      languageNamespaces: 
        - messages
      dualClient: false
    crypto:
      keystore:
        path: classpath:keystore.jwks
      signing:
        defaultSignerKeyId: rsa1
        defaultSigningAlgorithmName: RS256
      encrypt:
        defaultAlgorithm: RSA1_5
        defaultDecryptionKeyId: rsa1
        defaultEncryptionKeyId: rsa1
    jsonMessageSource:
      baseDirectory: classpath:/static/resources/js/locale/
    scheduling:
      enabled: true
      corePoolSize: 5
      tasks:
        clearExpiredTokens:
          fixedDelay: 30000
          initialDelay: 60000
        clearExpiredSites:
          fixedDelay: 30000
          initialDelay: 60000
        clearExpiredAuthorizationCodes:
          fixedDelay: 30000
          initialDelay: 60000
    endpoints:
      api:
        whitelist.enabled: true
        approvedsite.enabled: true
        blacklist.enabled: true
        client.enabled: true
        data.enabled: true
        token.enabled: true
        scope.enabled: true
        stats.enabled: true   
      oidc:
        dynamicclientregistration.enabled: false
        jwksetpublishing.enabled: false
        userinfo.enabled: false
        discovery.enabled: false
      protectedresourceregistration.enabled: false
         